[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.4", features = [ "derive" ] }
env_logger = "0.9"
glam = "0.22"
itertools = "0.10"
noise = "0.8"
pollster = "0.2"
rand = "0.8"
wgpu = "0.14"
winit = "0.27"
