[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.4", features = [ "derive" ] }
env_logger = "0.9.3"
glam = "0.22.0"
pollster = "0.2.5"
sdl2 = { version = "0.35.2", features = ["raw-window-handle"] }
wgpu = "0.13.1"
